//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MVVM_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public System.Guid MaHh { get; set; }
        public System.Guid MaDh { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public byte GiamGia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
