//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_MVVM_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Userss
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
